// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PTWee_SinKdnaConX.Models;

public partial class WCompanyRegister
{
    [Key]
    public int ID_Register { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nom_Company { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nom_Contact { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    public string Num_Tel { get; set; }
}