// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PTWee_SinKdnaConX.Models;

public partial class WeeCompanyContext : DbContext
{
    public WeeCompanyContext(DbContextOptions<WeeCompanyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<WCompanyRegister> WCompanyRegister { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WCompanyRegister>(entity =>
        {
            entity.HasKey(e => e.ID_Register).HasName("PK__WCompany__8EC6A706EBFE47B2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}